# Giai đoạn 1: Build Vue frontend
FROM node:18 as web-builder
WORKDIR /app
COPY main/manager-web/package*.json ./
RUN npm install
COPY main/manager-web .
RUN npm run build

# Giai đoạn 2: Build Java backend
FROM maven:3.9.4-eclipse-temurin-21 as api-builder
WORKDIR /app
COPY main/manager-api/pom.xml .
COPY main/manager-api/src ./src
RUN mvn clean package -Dmaven.test.skip=true

# Giai đoạn 3: Build image cuối cùng
FROM bellsoft/liberica-runtime-container:jre-21-glibc

# Cài đặt Nginx và thư viện font
RUN apk update && \
    apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
        nginx \
        bash \
        fontconfig \
        ttf-dejavu \
        msttcorefonts-installer \
    && ACCEPT_EULA=Y apk add --no-cache msttcorefonts-installer \
    && fc-cache -f -v \
    && rm -rf /var/cache/apk/*

# Cập nhật bộ nhớ cache font
RUN (printf 'YES\n' | update-ms-fonts || true) && fc-cache -f -v

# Cấu hình Nginx
COPY docs/docker/nginx.conf /etc/nginx/nginx.conf

# Sao chép sản phẩm build frontend
COPY --from=web-builder /app/dist /usr/share/nginx/html

# Sao chép file JAR backend Java
COPY --from=api-builder /app/target/xiaozhi-esp32-api.jar /app/xiaozhi-esp32-api.jar

# Mở cổng
EXPOSE 8002

# Script khởi động
COPY docs/docker/start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]
